// The media stram recording API is closely related to the media capture streams API and the WebRTCAPI.
// the api makes it possible to capture data generated by a mediaStream or HTMLMediaElement object which you can then process and save to disk
// to use the media recorder we need to pass it a stream
mediaRecorder = new MediaRecorder(stream);

// the dataavailable event gets called anytime there is media to be worked with
mediaRecorder.ondataavailable = handleDataAvailable // we write a function to handle this event

recorderChunks = []
handleDataAvailable = e => {

}
